name: mobile_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dropdown_formfield: ^0.1.3
  page_transition: ^2.0.2
  fluttertoast: ^8.0.8
  http: ^0.13.3
  intl: ^0.16.1
  animated_text_kit: ^4.2.1
  splashscreen: ^1.2.0
  animations: ^2.0.1
  provider: ^5.0.0
  flutter_local_notifications: ^8.2.0
  rxdart: ^0.27.1
  flutter_datetime_picker: ^1.5.1
  flutter_secure_storage: ^4.2.1
  flutter_multi_formatter: ^2.4.0
  dotted_line: ^3.0.0
  barcode: ^2.1.0
  flutter_svg: ^0.22.0
  syncfusion_flutter_barcodes: ^19.3.43
  badges: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: TTNorms-Regular
      fonts:
        - asset: assets/fonts/TTNorms-Regular.otf
    - family: TTNorms-Medium
      fonts:
        - asset: assets/fonts/TTNorms-Medium.otf
    - family: TTNorms-Bold
      fonts:
        - asset: assets/fonts/TTNorms-Bold.otf
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Text.ttf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf 
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf 
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf 
    - family: Sansation_Regular
      fonts:
        - asset: assets/fonts/Sansation_Regular.ttf 
          
